"""initial schema

Revision ID: cf90081ea3a0
Revises: 
Create Date: 2026-07-24 21:48:01.611857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf90081ea3a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'escalated', 'aborted', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('journey', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('phash', sa.String(), nullable=False),
    sa.Column('anchors', sa.JSON(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.create_index('ix_screens_phash', ['phash'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_screen', sa.Integer(), nullable=False),
    sa.Column('to_screen', sa.Integer(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_screen'], ['screens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_screen'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index('ix_edges_from_screen', ['from_screen'], unique=False)

    op.create_table('elements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('norm_text', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.create_index('ix_elements_norm_text', ['norm_text'], unique=False)
        batch_op.create_index('ix_elements_screen_id', ['screen_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_index('ix_elements_screen_id')
        batch_op.drop_index('ix_elements_norm_text')

    op.drop_table('elements')
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index('ix_edges_from_screen')

    op.drop_table('edges')
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.drop_index('ix_screens_phash')

    op.drop_table('screens')
    op.drop_table('execution_runs')
    # ### end Alembic commands ###
