from __future__ import annotations

import hashlib
import json
import os
import plistlib
import shutil
import subprocess
import sys
import sysconfig
import tempfile
import time
from dataclasses import dataclass
from enum import Enum
from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as distribution_version
from pathlib import Path

from choto import userpaths
from choto.log import get_logger
from choto.mcpserver.socket_path import SOCKET_OPTION

_log = get_logger(__name__)


BUNDLE_IDENTIFIER = "com.choto.daemon"

BUNDLE_DISPLAY_NAME = "Choto"

BUNDLE_DIRNAME = "Choto.app"
EXECUTABLE_NAME = "choto-daemon"
BOOTSTRAP_NAME = "bootstrap.py"
MANIFEST_NAME = "build.json"

DEFAULT_BUNDLE_DIR = userpaths.MACOS_APPLICATION_SUPPORT / userpaths.APP_DIR_NAME

MINIMUM_MACOS_VERSION = "13.0"

INFO_DICTIONARY_VERSION = "6.0"

EXECUTABLE_MODE = 0o755
BUNDLE_DIR_MODE = 0o755
_READ_CHUNK_BYTES = 1024 * 1024


CHECK_PERMISSION_FLAG = "--check-input-permission"
REPORT_TO_OPTION = "--report-to"
PERMISSION_REPORT_KEY = "granted"
_REPORT_FILENAME = "input-permission.json"


CODESIGN = "/usr/bin/codesign"
CODESIGN_TIMEOUT_SECONDS = 120.0

OPEN = "/usr/bin/open"
OPEN_TIMEOUT_SECONDS = 30.0
PERMISSION_REPORT_TIMEOUT_SECONDS = 30.0
PERMISSION_POLL_INTERVAL_SECONDS = 0.05


class BundleError(RuntimeError): ...


class InputPermission(str, Enum):
    GRANTED = "granted"
    DENIED = "denied"
    UNKNOWN = "unknown"


@dataclass(frozen=True)
class BundleBuild:
    path: Path
    executable: Path
    bootstrap: Path
    changed: bool


def bundle_path(bundle_dir: Path | None = None) -> Path:
    root = DEFAULT_BUNDLE_DIR.expanduser() if bundle_dir is None else bundle_dir
    return root / BUNDLE_DIRNAME


def executable_path(bundle: Path) -> Path:
    return bundle / "Contents" / "MacOS" / EXECUTABLE_NAME


def bootstrap_path(bundle: Path) -> Path:
    return bundle / "Contents" / "Resources" / BOOTSTRAP_NAME


def info_plist_path(bundle: Path) -> Path:
    return bundle / "Contents" / "Info.plist"


def manifest_path(bundle: Path) -> Path:
    return bundle / "Contents" / "Resources" / MANIFEST_NAME


def daemon_argv(bundle: Path, socket_path: Path) -> list[str]:
    return [
        str(executable_path(bundle)),
        str(bootstrap_path(bundle)),
        SOCKET_OPTION,
        str(socket_path),
    ]


def interpreter_source() -> Path:
    raw = getattr(sys, "_base_executable", None) or sys.executable
    if not raw:
        raise BundleError("the running interpreter has no executable path to copy")
    path = Path(raw)
    if not path.is_file():
        raise BundleError(f"interpreter {path} does not exist; cannot build the app bundle")
    return path


def site_packages() -> Path:
    path = Path(sysconfig.get_path("purelib"))
    if not path.is_absolute():
        raise BundleError(f"site-packages path {path} is not absolute")
    if not path.is_dir():
        raise BundleError(
            f"site-packages directory {path} does not exist; build the app bundle from "
            "the project virtualenv (e.g. `uv run choto service install`)"
        )
    return path


def package_version() -> str:
    try:
        return distribution_version("choto")
    except PackageNotFoundError as exc:
        raise BundleError(
            "the choto distribution is not installed in this environment, so the "
            "app bundle has no version to declare; run `uv sync` first"
        ) from exc


def build_info_plist(version: str) -> dict[str, object]:
    return {
        "CFBundleIdentifier": BUNDLE_IDENTIFIER,
        "CFBundleName": BUNDLE_DISPLAY_NAME,
        "CFBundleDisplayName": BUNDLE_DISPLAY_NAME,
        "CFBundleExecutable": EXECUTABLE_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleInfoDictionaryVersion": INFO_DICTIONARY_VERSION,
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "LSMinimumSystemVersion": MINIMUM_MACOS_VERSION,
        "LSUIElement": True,
    }


def render_info_plist(version: str) -> bytes:
    return plistlib.dumps(build_info_plist(version), fmt=plistlib.FMT_XML)


_BOOTSTRAP_TEMPLATE = '''\
"""Entry point of Choto.app — generated by choto.mcpserver.appbundle.

Do not edit: the file is overwritten on every rebuild and sealed by the
bundle's code signature.

The bundle's main executable is a copy of the project interpreter, so it starts
with its standard library but without the virtualenv. The virtualenv is
registered as a *site* directory rather than appended to ``sys.path`` because
only that runs the ``.pth`` hooks — which is how an editable install of
``choto`` becomes importable.
"""

import site
import sys

site.addsitedir({site_packages!r})

from choto.mcpserver.__main__ import main  # noqa: E402  (needs the path above)

sys.exit(main(sys.argv[1:]))
'''


def render_bootstrap(site_packages_path: Path) -> str:
    if not site_packages_path.is_absolute():
        raise BundleError(f"site-packages path must be absolute, got {site_packages_path}")
    return _BOOTSTRAP_TEMPLATE.format(site_packages=str(site_packages_path))


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            while chunk := handle.read(_READ_CHUNK_BYTES):
                digest.update(chunk)
    except OSError as exc:
        raise BundleError(f"cannot read {path}: {exc}") from exc
    return digest.hexdigest()


def _render_manifest(
    *, version: str, interpreter_digest: str, info_plist: bytes, bootstrap: str
) -> bytes:
    return json.dumps(
        {
            "identifier": BUNDLE_IDENTIFIER,
            "version": version,
            "interpreter_sha256": interpreter_digest,
            "info_plist_sha256": _sha256_bytes(info_plist),
            "bootstrap_sha256": _sha256_bytes(bootstrap.encode("utf-8")),
        },
        sort_keys=True,
        indent=2,
    ).encode("utf-8")


def _run_tool(argv: list[str], *, timeout: float) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            argv,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired as exc:
        raise BundleError(f"`{' '.join(argv)}` gave no answer within {timeout}s") from exc
    except OSError as exc:
        raise BundleError(f"`{' '.join(argv)}` could not be run: {exc}") from exc


def sign(bundle: Path) -> None:
    argv = [
        CODESIGN,
        "--force",
        "--sign",
        "-",
        "--identifier",
        BUNDLE_IDENTIFIER,
        str(bundle),
    ]
    completed = _run_tool(argv, timeout=CODESIGN_TIMEOUT_SECONDS)
    if completed.returncode != 0:
        raise BundleError(
            f"codesign refused to sign {bundle} (exit {completed.returncode}): "
            f"{completed.stderr.strip()}"
        )
    _log.info("appbundle.signed", bundle=str(bundle), identifier=BUNDLE_IDENTIFIER)


def signature_status(bundle: Path) -> tuple[bool, str | None]:
    if not bundle.is_dir():
        return False, f"no bundle at {bundle}"
    completed = _run_tool([CODESIGN, "--verify", str(bundle)], timeout=CODESIGN_TIMEOUT_SECONDS)
    if completed.returncode == 0:
        return True, None
    return (
        False,
        completed.stderr.strip() or f"codesign --verify exited with {completed.returncode}",
    )


def _is_current(bundle: Path, manifest: bytes) -> bool:
    required = (
        info_plist_path(bundle),
        executable_path(bundle),
        bootstrap_path(bundle),
        manifest_path(bundle),
    )
    if not all(path.is_file() for path in required):
        return False
    try:
        if manifest_path(bundle).read_bytes() != manifest:
            return False
    except OSError as exc:
        raise BundleError(f"cannot read the build manifest of {bundle}: {exc}") from exc
    signed, _ = signature_status(bundle)
    return signed


@dataclass(frozen=True)
class _Contents:
    interpreter: Path
    site_packages: Path
    version: str
    info_plist: bytes
    bootstrap: str
    manifest: bytes


def _compose(interpreter: Path, packages: Path, version: str) -> _Contents:
    if not interpreter.is_absolute():
        raise BundleError(f"interpreter path must be absolute, got {interpreter}")

    info_plist = render_info_plist(version)
    bootstrap = render_bootstrap(packages)
    return _Contents(
        interpreter=interpreter,
        site_packages=packages,
        version=version,
        info_plist=info_plist,
        bootstrap=bootstrap,
        manifest=_render_manifest(
            version=version,
            interpreter_digest=_sha256_file(interpreter),
            info_plist=info_plist,
            bootstrap=bootstrap,
        ),
    )


def _stage(staging: Path, contents: _Contents) -> None:
    macos = staging / "Contents" / "MacOS"
    resources = staging / "Contents" / "Resources"
    try:
        macos.mkdir(parents=True)
        resources.mkdir(parents=True)
        (staging / "Contents" / "Info.plist").write_bytes(contents.info_plist)
        shutil.copyfile(contents.interpreter, macos / EXECUTABLE_NAME)
        (macos / EXECUTABLE_NAME).chmod(EXECUTABLE_MODE)
        (resources / BOOTSTRAP_NAME).write_text(contents.bootstrap, encoding="utf-8")
        (resources / MANIFEST_NAME).write_bytes(contents.manifest)
    except OSError as exc:
        raise BundleError(f"cannot lay out the app bundle in {staging}: {exc}") from exc


def _materialize(target: Path, contents: _Contents) -> None:
    try:
        target.parent.mkdir(parents=True, exist_ok=True, mode=BUNDLE_DIR_MODE)
    except OSError as exc:
        raise BundleError(f"cannot create {target.parent}: {exc}") from exc

    staging = Path(tempfile.mkdtemp(prefix=".choto-bundle-", dir=target.parent)) / BUNDLE_DIRNAME
    try:
        _stage(staging, contents)
        sign(staging)
        _replace(target, staging)
    finally:
        shutil.rmtree(staging.parent, ignore_errors=True)


def _built(target: Path, *, changed: bool) -> BundleBuild:
    return BundleBuild(
        path=target,
        executable=executable_path(target),
        bootstrap=bootstrap_path(target),
        changed=changed,
    )


def build(
    *,
    bundle_dir: Path | None = None,
    interpreter: Path | None = None,
    site_packages_path: Path | None = None,
    version: str | None = None,
) -> BundleBuild:
    contents = _compose(
        interpreter_source() if interpreter is None else interpreter,
        site_packages() if site_packages_path is None else site_packages_path,
        package_version() if version is None else version,
    )

    target = bundle_path(bundle_dir)
    if _is_current(target, contents.manifest):
        _log.info("appbundle.unchanged", bundle=str(target))
        return _built(target, changed=False)

    _materialize(target, contents)
    _log.info(
        "appbundle.built",
        bundle=str(target),
        identifier=BUNDLE_IDENTIFIER,
        version=contents.version,
        interpreter=str(contents.interpreter),
        site_packages=str(contents.site_packages),
    )
    return _built(target, changed=True)


def _replace(target: Path, staging: Path) -> None:
    try:
        if target.exists():
            shutil.rmtree(target)
        os.rename(staging, target)
    except OSError as exc:
        raise BundleError(f"cannot install the app bundle at {target}: {exc}") from exc


def check_input_permission(
    bundle: Path, *, timeout_seconds: float = PERMISSION_REPORT_TIMEOUT_SECONDS
) -> tuple[InputPermission, str | None]:
    bootstrap = bootstrap_path(bundle)
    if not executable_path(bundle).is_file() or not bootstrap.is_file():
        return InputPermission.UNKNOWN, f"no app bundle at {bundle}; run `choto service install`"

    with tempfile.TemporaryDirectory(prefix="choto-permission-") as scratch:
        report = Path(scratch) / _REPORT_FILENAME
        refusal = _ask_bundle_to_report(bundle, bootstrap, report)
        if refusal is not None:
            return InputPermission.UNKNOWN, refusal
        return _await_permission_report(report, timeout_seconds=timeout_seconds)


def _ask_bundle_to_report(bundle: Path, bootstrap: Path, report: Path) -> str | None:
    argv = [
        OPEN,
        "-n",
        "-a",
        str(bundle),
        "--args",
        str(bootstrap),
        CHECK_PERMISSION_FLAG,
        REPORT_TO_OPTION,
        str(report),
    ]
    completed = _run_tool(argv, timeout=OPEN_TIMEOUT_SECONDS)
    if completed.returncode == 0:
        return None
    return (
        f"LaunchServices refused to start {bundle}: "
        f"{completed.stderr.strip() or f'open exited with {completed.returncode}'}"
    )


def _await_permission_report(
    report: Path, *, timeout_seconds: float
) -> tuple[InputPermission, str | None]:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        if report.is_file():
            return _read_permission_report(report)
        time.sleep(PERMISSION_POLL_INTERVAL_SECONDS)
    return InputPermission.UNKNOWN, (
        f"the app bundle did not report its input permission within {timeout_seconds}s"
    )


def _read_permission_report(report: Path) -> tuple[InputPermission, str | None]:
    try:
        payload = json.loads(report.read_text(encoding="utf-8"))
    except OSError as exc:
        return InputPermission.UNKNOWN, f"cannot read the permission report: {exc}"
    except json.JSONDecodeError as exc:
        return InputPermission.UNKNOWN, f"the permission report is not JSON: {exc}"

    if not isinstance(payload, dict) or not isinstance(payload.get(PERMISSION_REPORT_KEY), bool):
        return InputPermission.UNKNOWN, f"unexpected permission report: {payload!r}"

    if payload[PERMISSION_REPORT_KEY]:
        return InputPermission.GRANTED, None
    return InputPermission.DENIED, (
        f"macOS has not granted Accessibility to {BUNDLE_IDENTIFIER}; approve the "
        '"Choto wants to control your computer" prompt'
    )


def write_permission_report(report: Path, *, granted: bool) -> None:
    payload = json.dumps({PERMISSION_REPORT_KEY: granted}, sort_keys=True).encode("utf-8")
    partial = report.with_name(report.name + ".partial")
    try:
        partial.write_bytes(payload)
        os.replace(partial, report)
    except OSError as exc:
        raise BundleError(f"cannot write the permission report to {report}: {exc}") from exc
